//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestiranjeZavrsni.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kolekcija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kolekcija()
        {
            this.Tests = new HashSet<Test>();
        }
    
        public int id { get; set; }
        public int pitanje1 { get; set; }
        public int pitanje2 { get; set; }
        public int pitanje3 { get; set; }
        public int pitanje4 { get; set; }
        public int pitanje5 { get; set; }
        public int pitanje6 { get; set; }
        public int pitanje7 { get; set; }
        public int pitanje8 { get; set; }
        public int pitanje9 { get; set; }
        public int pitanje10 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test> Tests { get; set; }
    }
}
