//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestiranjeZavrsni.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public int id { get; set; }
        public int korisnik { get; set; }
        public Nullable<System.DateTime> vrijeme { get; set; }
        public int rezultat { get; set; }
        public int kategorija { get; set; }
        public int kolekcija { get; set; }
    
        public virtual Kategorija Kategorija1 { get; set; }
        public virtual Kolekcija Kolekcija1 { get; set; }
        public virtual User User { get; set; }
    }
}
